### ISSUE TITLE
怎么把class-validator验证的错误添加到自定义的response中呢？

### ISSUE THREAD

**Issue by AHRL** [unix/koa-ts#16]
Type:
- [x] Help   

Description:
在class-validator中数据库验证失败的情况下，怎么把class-validator的错误添加到自定义的response中呢？
我想有一个统一的返回格式，请问作者大大知道怎么写吗？看了class-validator的文档也不太明白，谢谢作者大大～

**Comment by unix** [comment]
数据库验证失败的信息需要在 `entity` 中自定义错误信息。
@l1shen 有什么意见 🙂

**Comment by l1shen** [comment]
@AHRL 你可以手动从 `class-validator` 中 `import validate` 验证
```
import {validate} from "class-validator";

validate(post).then(errors => {
    // ...
});
```
