### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by majinhui04** [unix/koa-ts#30]
Type:
- [ x ] Bug
- [ ] Feature
- [x] Help   

Description:
ts配置中的`emitDeclarationOnly`导致编译失败
TS5069: Option 'emitDeclarationOnly' cannot be specified without specifying option 'declaration' or option 'composite'.

删除后可以编译成功，但是启动服务时又报错 `NODE_ENV=development node releases/index`：
import Environment from 'configs/environments'
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by unix** [comment]
这是因为 `orm-config` 只能读取相对于 `node_modules` 目录的根目录配置文件引起的，我已经在 #33 中使用内置的转发修复了此问题。同时现在 TS 能够直接编译出比较好的效果，不再需要 `ncc`，也已经移除。

现在 `database` 配置仍旧在 `configs` 中，没有任何改变。这里的改动只是将 `orm` 读取配置从环境文件转到了内置。
