### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by huangguanhua121** [unix/koa-ts#31]
E:\ts\koa-ts>yarn dev
yarn run v1.22.0
$ export NODE_ENV=development; nodemon --config nodemon.json
'export' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by unix** [comment]
windows 不支持 `export`，你可以改一下: `set NODE_ENV= development`。
或者在 windows 中使用 WSL2。
