### ISSUE TITLE
run to stop

### ISSUE THREAD

**Issue by lianshao123** [unix/koa-ts#34]
Type:- [ ] Help   

Console:
PS C:\Users\LENOVO\Desktop\数字权益平台\test\koa-ts> yarn
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > routing-controllers@0.8.1" has incorrect peer dependency "class-validator@0.10.1".
[5/5] Building fresh packages...
Done in 22.50s.
yarn run v1.22.10
$ export NODE_ENV=development; nodemon --config nodemon.json
'export' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\LENOVO\Desktop\数字权益平台\test\koa-ts> yarn dev
yarn run v1.22.10
$ set NODE_ENV=development; nodemon --config nodemon.json
Done in 0.13s.

Description:
34/5000
node:v12.21.0
I'm using Windows, but when I run the "yarn dev" command I get "export NODE_ENV=development; "Nodemon --config nodemon. Json" exception.Then I changed the expost in the package.json file to set.Run the "yarn dev" command.As a result, the program terminated.

**Comment by unix** [comment]
命令都是用 `shell` 写的，暂时没有支持 windows。
在 windows 平台推进你使用 WSL2 的工作方式，不仅可以兼容类似命令问题，也有非常高的工作体验。
