### ISSUE TITLE
请教一下ConnectionManager的用法

### ISSUE THREAD

**Issue by Asteroid77** [unix/koa-ts#36]
Type:
- [ ] Bug
- [ ] Feature
- [x] Help   

Description:
> 数据库：Mysql 5.7

我在使用Repository的过程中遇到一些小问题：
首先我定义了一个Service，在对应的Controller中调用Service时出现`ConnectionNotFoundError: Connection "default" was not found.`报错，打断点排查发现走至constructor给reponsitory赋值的这一步就出现了异常。
```
@Service()
export class IpProxyService {
    repository:Repository<IpProxy>
    constructor() {
        this.repository = getRepository(IpProxy)
    }
     ..............
}
```
经过排查以及查阅官方文档，我发现系`connection.ts`中定义的`connectionManager`初始化方式的差异所致：
在大大的项目中，使用的是`new ConnectionManager()`方法，而如果需要像大大给的`session.service.ts`演示中的Repository使用方法一致的话，需要变成`getConnectionManager()`，**与您在`session.services.ts`中演示的不一致。**

[以下摘自TypeORM文档](https://typeorm.io/#/connection/using-connectionmanager)
This is not a general way of creating a connection, but it may be useful for some users. For example, users who want to create connection and store its instance, but have to control when the actual "connection" will be established. Also you can create and maintain your own ConnectionManager:
```
import {getConnectionManager, ConnectionManager, Connection} from "typeorm";

const connectionManager = new ConnectionManager();

const connection = connectionManager.create({
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "test",
    password: "test",
    database: "test",
});
await connection.connect(); // performs connection
```
But note, this way you won't be able to use getConnection() anymore - you'll need to store your connection manager instance and use connectionManager.get to get a connection you need.

Generally avoid this method and avoid unnecessary complications in your application, use ConnectionManager only if you really think you need it.

文档中说到`new ConnectionManager();` 并不是一个比较常见的用法，需要开发者自己手动存储这个`ConnectionManager`实例（比如说挂载在global上），然后在各个地方引用才可以使用。

使用这种方式连接，在我个人的理解里面，使用的过程中应该是不能使用typeorm提供的那些方法去获取`getConnection`以及`getRepository`，需要直接维护/获取存储的`ConnectionManager`实例。

**不知道是不是我使用上出现了问题，麻烦大大看这一大片文字了。**

**Comment by Asteroid77** [comment]
已解决：
1. 在controller中，不要在Class外调用Service。
```
//比如说:
// const monitorService = new MonitorService()  在这里定义Service是不对的

@JsonController()
export class MonitorController {
  constructor() {
  }
  @Get('/monitor/test')
  async GetProxy() : Promise<any> {
    // return await monitorService.GetIpProxy()
  }

  @Get('/monitor/exec')
  async execMultiMonitorGraphicsCard(): Promise<any> {
    // 应该在controller类里面的方法中定义
    const ipProxyService = new IpProxyService()
    return await ipProxyService.Test()
  }
}
```
2.  connections.ts中连接的方式需注意：
官网中提到：
> This is not a general way of creating a connection, but it may be useful for some users. For example, users who want to create connection and store its instance, but have to control when the actual "connection" will be established. Also you can create and maintain your own ConnectionManager:
```
import {getConnectionManager, ConnectionManager, Connection} from "typeorm";

const connectionManager = new ConnectionManager();
const connection = connectionManager.create({
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "test",
    password: "test",
    database: "test",
});
await connection.connect(); // performs connection
```
But note, **this way you won't be able to use getConnection() anymore** - **you'll need to store your connection manager instance and use connectionManager.get to get a connection you need.**

**Generally avoid this method and avoid unnecessary complications in your application, use ConnectionManager only if you really think you need it.**

看这段话，应该是说："如果使用`new ConnectionManager()`这种方法创建连接，则无法像我想象的那样直接使用`getRepository(Entity)`这样去获取Repository，而是需要通过其他手段来获取。" 
由于已经处在深夜，我并没有继续纠结这个问题，而是直接使用了第一种常用的方式，也就是`getConnectionManager()`代替了项目中原本的`new ConnectionManager()`，获取不到default connect的问题已经得到解决。

**Comment by unix** [comment]
这个的确很麻烦，`ConnectionManager` 是为了能够用自定义的方式更科学的从文件中加载环境变量，但是不能自动维护实例。

我刚刚更新到了 `v3.1.0` 版本，使用 `Prisma` 代替了 `typeorm`，现在可以不用考虑这些问题，`Prisma` 会在需要时自动开始链接。除此之外，迁移到 `Prisma` 后，应用启动内存至少下降到原来的 `1/5` 或者更少，这是因为 `type-orm` 会直接加载非常多不需要的数据库适配器导致的，详见这里：#19

`Prisma` 是现代化的智能 ORM，包含自动化的数据库迁移与类型推断，也是在 TypeScript 生态中操作 Database 的最佳实践与未来的主流方向，非常酷，希望你能喜欢这个升级。

----

有几个注意事项：

1. 在创建新项目之后，你可以需要使用 Docker 挂起 Postgres SQL: `yarn compose`。（或是任何你的自定义镜像）
2. 确保 Docker 挂起后，你需要至少运行 `prisma migrate dev` 来迁移数据模型，运行 `prisma generate` 来生成 TypeScript 使用的类型文件。(请看 README.md)
3. 在生产部署时，会自动迁移，无需管理数据库。

**Comment by Asteroid77** [comment]
好的，非常感谢大大的帮助 :)
