### ISSUE TITLE
在PRODUCTION模式下，controller无法访问到service

### ISSUE THREAD

**Issue by Xy2002** [unix/koa-ts#68]
Type:
- [ ] Bug
- [ ] Feature
- [x] Help   

Description:

在env=DEVELOPMENT模式下运行，没有任何的问题  
但是如果在env=PRODUCTION模式下运行时，controller访问service的函数时，是`undefined`

例如：
```TypeScript

import { UserService } from '../services'

@JsonController()
@Service()
export class UserController {

  constructor(private userSerivce: UserService) { }

  @Post('/user/login')
  async login(
    @BodyParam('code') code: string
  ): Promise<any> {
    if (!code) {
      throw new BadRequestError('code is required')
    }
    let res = await this.userSerivce.loginByCode(code)
    console.log(this.userSerivce.loginByCode) // undefined
    return res
  }
}
```

**Comment by ITLove520** [comment]
constructor(private userSerivce: UserService) { 
    this.userService = new UserService();
}
加一行代码

**Comment by Xy2002** [comment]
> constructor(private userSerivce: UserService) { this.userService = new UserService(); } 加一行代码

这非常有用，谢谢！
